# Easypanel Configuration
name: wazilrest-frontend
type: app

build:
  context: .
  dockerfile: Dockerfile

services:
  - name: web
    image: ${IMAGE}
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
