# Easypanel Nixpacks Configuration
[phases.setup]
  nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
  cmds = [
    "npm ci --legacy-peer-deps --omit=optional || npm install --legacy-peer-deps --omit=optional",
    "npm install https-proxy-agent socks-proxy-agent"
  ]

[phases.build]
  cmds = ["npm run build"]

[variables]
  NODE_ENV = "production"
  NPM_CONFIG_LOGLEVEL = "error"

[start]
  cmd = "npm start"

[staticAssets]
  "public" = "./"
